name: AwesomeEnchantCommands
main: com.emiv.awesomeenchantcommands.Main
version: 1.2
api-version: 1.16
commands:
  awesomeenchantcommands:
    aliases: [aec, awesomeec]
    description: Main command for AwesomeEnchantCommands
  fortune:
    aliases:
    description: Fortune command
  protection:
    aliases:
    description: Protection command
  thorns:
    aliases:
    description: Thorns command
  featherfalling:
    aliases:
    description: Feather Falling command
  knockback:
    aliases:
    description: Knockback command
  looting:
    aliases:
    description: Looting command
  infinity:
    aliases:
    description: Infinity command
  sharpness:
    aliases:
    description: Sharpness command